name: Pruebas CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Construcción del artefacto
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Ejecutar pruebas
        run: ./gradlew test
